### ISSUE TITLE
Customisable root directory

### ISSUE THREAD

**Issue by mottosso** [mottosso/be#41]
Be default, `be` considers the current working directory as the root of your projects.

### Goal

Make this customisable by specifying `BE_CWD`.

**Windows**

```bash
$ set BE_CWD=c:\my\custom\path
$ be in project here instead
```

**Unix**

```bash
$ export BE_CWD=/my/custom/path
$ be in project here instead
$ # or
$ BE_CWD=/my/custom/path be in project here instead
```

**Comment by mdilena** [comment]
hey Marcus, when I made the pull request I was actually looking forward to request this exact feature! So thanks for providing that :) I'll try it out tonight
